"""Measure whether the AI and mesh layers actually earn their place.

    python scripts/evaluate.py              # ~1 minute
    python scripts/evaluate.py --seeds 60   # tighter confidence intervals

The ablation table in the write-up counts how many nodes changed band. That is
activity, not accuracy. This script asks the question a judge asks: given a
frame, does the system say "event" when there is one, and stay quiet when
there is not?

Three questions, three tables: does it stay quiet when nothing is happening;
does it refuse to cry wolf when one instrument breaks; and does it still see a
real event.

Method. A frame is 20 nodes generated by the project's own simulator at a
fixed time of day with one noise seed. A *negative* frame has no scenario
applied. A *positive* frame has one scenario applied at an intensity between
0 and 1, using the same delta table the demo uses (intensity 1.0 is exactly
the published demo frame). A frame counts as detected when at least one node
raises a WARNING or CRITICAL alert *for that scenario's hazard*; on a negative
frame any WARNING or CRITICAL at all is a false alarm. Labels are therefore
frame-level and come from what was injected, not from a judgement about
individual nodes.

Three configurations are compared on identical frames:

    sub-scores      the six hazard sub-scores alone -- the "just thresholds"
                    baseline any reviewer would ask about
    + AI            sub-scores multiplied by the Isolation Forest's verdict
    + AI + mesh     the shipped system, including the corroboration rule that
                    refuses to raise a hazard alert no neighbour agrees with

Everything is seeded, so two runs print the same table. Check that: run it
twice and diff the output.
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
os.environ.setdefault("CLIMATE_MESH_DB",
                      str(Path(tempfile.gettempdir()) / "climate_mesh_evaluate.db"))

from ai.anomaly_model import AnomalyDetector          # noqa: E402
from backend.risk_engine import (UNCORROBORATED, WARNING, CRITICAL,  # noqa: E402
                                 calculate_base, compute_all, risk_level)
from config.nodes import NODES                        # noqa: E402
from sensors.base import make_reading                 # noqa: E402
from simulation.engine import _CLAMP, generate_channels  # noqa: E402
from simulation.scenarios import scenario_delta       # noqa: E402

HAZARD_OF = {"flood": "flood", "heatwave": "heatwave", "smog": "smog",
             "storm": "storm"}
ALERTING = (WARNING, CRITICAL)
TICK = 0.0          # fixed time of day, so intensity is the only thing moving
STUCK_WATER_M = 9.0  # a jammed ultrasonic water sensor reading right through


def frame(scenario: str, intensity: float, seed: int,
          stuck: str | None = None) -> list[dict]:
    """One 20-node frame with ``scenario`` applied at ``intensity`` (0..1).

    ``stuck`` names a node whose water-level channel is jammed at 9 m, the
    classic failure of a cheap ultrasonic sensor that has been knocked,
    blocked or flooded itself.
    """
    readings = []
    for node in NODES:
        # deterministic=True is what actually honours `seed`: with it False the
        # simulator returns an unseeded random.Random() and the seed argument
        # does nothing, which made this whole table irreproducible.
        values = generate_channels(node, TICK, "none", deterministic=True, seed=seed)
        if scenario != "none" and intensity > 0:
            for channel in list(values):
                delta = scenario_delta(scenario, node["environment"], channel)
                if delta:
                    lo, hi = _CLAMP[channel]
                    values[channel] = max(lo, min(hi, values[channel] + delta * intensity))
        if stuck is not None and node["node_id"] == stuck:
            values["water_level"] = STUCK_WATER_M
        readings.append(make_reading(node, source="simulation", scenario=scenario,
                                     **values))
    return readings


def verdicts(readings: list[dict], detector: AnomalyDetector) -> dict[str, set[str]]:
    """Hazards alerted by each configuration for this frame."""
    full = compute_all(readings, detector)
    # Score the frame once and reuse the verdicts, exactly as the engine does.
    ai_verdicts = detector.predict_many(readings)
    bases = {r["node_id"]: calculate_base(r, detector, v)
             for r, v in zip(readings, ai_verdicts)}

    subs, ai, mesh = set(), set(), set()
    for result in full:
        base = bases[result["node_id"]]
        if risk_level(round(base["base_score"], 1)) in ALERTING:
            subs.add(base["dominant_hazard"])
        if risk_level(round(base["base_score"] * base["ai_multiplier"], 1)) in ALERTING:
            ai.add(base["dominant_hazard"])
        # The shipped system: an uncorroborated node raises a sensor-check,
        # not the hazard, so it must not count as a detection of the hazard.
        if (result["level"] in ALERTING
                and result["corroboration"] != UNCORROBORATED):
            mesh.add(result["dominant_hazard"])
    return {"sub-scores": subs, "+ AI": ai, "+ AI + mesh": mesh}


def main() -> int:
    ap = argparse.ArgumentParser(description="Detection and false-alarm rates")
    ap.add_argument("--seeds", type=int, default=30,
                    help="noise realisations per point (default 30)")
    ap.add_argument("--step", type=float, default=0.1,
                    help="intensity step (default 0.1)")
    args = ap.parse_args()

    from data.database import init_db, reset_db
    init_db(); reset_db()

    print("=" * 76)
    print("  Climate Mesh — does each layer earn its place?")
    print("=" * 76)
    detector = AnomalyDetector().train(quiet=True)
    configs = ["sub-scores", "+ AI", "+ AI + mesh"]
    seeds = list(range(1000, 1000 + args.seeds))
    scenarios = list(HAZARD_OF)

    # --- False alarms on quiet frames ------------------------------------
    false_alarms = {c: 0 for c in configs}
    for seed in seeds:
        got = verdicts(frame("none", 0.0, seed), detector)
        for c in configs:
            if got[c]:
                false_alarms[c] += 1
    print(f"\n  Quiet frames ({len(seeds)} frames, no event injected)")
    print("  " + "-" * 62)
    print(f"  {'configuration':<16}{'false alarms':>14}{'rate':>10}")
    for c in configs:
        n = false_alarms[c]
        print(f"  {c:<16}{n:>8} / {len(seeds):<4}{n / len(seeds):>9.1%}")

    # --- One broken instrument, nothing else happening --------------------
    # This is what neighbour agreement is for. Every configuration sees the
    # same impossible reading; only the shipped one asks whether anyone else
    # can see it.
    cried_wolf = {c: 0 for c in configs}
    trials = 0
    for seed in seeds:
        for node_id in ("REGENTS-CANAL", "RIVER-LEA", "PUTNEY"):
            got = verdicts(frame("none", 0.0, seed, stuck=node_id), detector)
            trials += 1
            for c in configs:
                if "flood" in got[c]:
                    cried_wolf[c] += 1
    print(f"\n  One stuck water sensor (9 m) in an otherwise calm mesh"
          f" ({trials} frames)")
    print("  " + "-" * 62)
    print(f"  {'configuration':<16}{'false flood alerts':>20}{'rate':>10}")
    for c in configs:
        n = cried_wolf[c]
        print(f"  {c:<16}{n:>14} / {trials:<4}{n / trials:>9.1%}")

    # --- Detection against event intensity --------------------------------
    steps = [round(i * args.step, 2)
             for i in range(1, int(round(1.0 / args.step)) + 1)]
    print(f"\n  Detection rate by event intensity"
          f" ({len(seeds)} frames per scenario per step, 4 scenarios)")
    print("  " + "-" * 62)
    header = "  intensity   " + "".join(f"{c:>16}" for c in configs)
    print(header)
    first_full = {c: None for c in configs}
    for intensity in steps:
        hits = {c: 0 for c in configs}
        total = 0
        for scenario in scenarios:
            for seed in seeds:
                got = verdicts(frame(scenario, intensity, seed), detector)
                total += 1
                for c in configs:
                    if HAZARD_OF[scenario] in got[c]:
                        hits[c] += 1
        row = f"  {intensity:>9.2f}   "
        for c in configs:
            rate = hits[c] / total
            if first_full[c] is None and rate >= 0.9:
                first_full[c] = intensity
            row += f"{rate:>15.1%} "
        print(row)

    print("\n  Intensity at which each configuration first reaches 90 % detection")
    print("  " + "-" * 62)
    for c in configs:
        got = first_full[c]
        print(f"  {c:<16}{'never' if got is None else f'{got:.2f}':>12}")
    baseline, full = first_full["sub-scores"], first_full["+ AI + mesh"]
    if baseline is not None and full is not None and full < baseline:
        print(f"\n  The full system reaches 90 % detection at intensity {full:.2f},"
              f" where\n  thresholds alone need {baseline:.2f}"
              f" — it sees the same event earlier.")
    elif baseline is not None and full is not None and full == baseline:
        print("\n  Both reach 90 % detection at the same intensity; the layers buy"
              "\n  confidence and explanation here rather than earlier detection.")
    print("=" * 76)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
